# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    resolvers :
        default :
            web_path : ~

    filter_sets:
        cache : ~

        thumb:
            quality: 75
            filters:
                thumbnail:
                    size: [510, 242]
                    mode: outbound

        thumb_large:
            quality: 75
            filters:
                thumbnail:
                    size: [1035, 440]
                    mode: outbound

        feature:
            quality: 75
            filters:
                thumbnail:
                    size: [292, 143]
                    mode: outbound

        medium:
            quality: 75
            filters:
                thumbnail:
                    size: [1035, 440]
                    mode: outbound

